// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5OtYeU0Ve6rvaMUA1hoRBpSq3qPaUdio',
    appId: '1:240028515315:web:fa71d6fd6c06018a4ff086',
    messagingSenderId: '240028515315',
    projectId: 'resqnow-12e6c',
    authDomain: 'resqnow-12e6c.firebaseapp.com',
    storageBucket: 'resqnow-12e6c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnltRtPDxFyr4KhY0gDi5S3ydGarmBsc',
    appId: '1:240028515315:android:f91928a440f377344ff086',
    messagingSenderId: '240028515315',
    projectId: 'resqnow-12e6c',
    storageBucket: 'resqnow-12e6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMQwdf16RsOWiM-8XAG7adgl1lXyAhonw',
    appId: '1:240028515315:ios:32c9eb9bc6c1349f4ff086',
    messagingSenderId: '240028515315',
    projectId: 'resqnow-12e6c',
    storageBucket: 'resqnow-12e6c.firebasestorage.app',
    iosBundleId: 'com.example.resqnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMQwdf16RsOWiM-8XAG7adgl1lXyAhonw',
    appId: '1:240028515315:ios:32c9eb9bc6c1349f4ff086',
    messagingSenderId: '240028515315',
    projectId: 'resqnow-12e6c',
    storageBucket: 'resqnow-12e6c.firebasestorage.app',
    iosBundleId: 'com.example.resqnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5OtYeU0Ve6rvaMUA1hoRBpSq3qPaUdio',
    appId: '1:240028515315:web:b69ec7fc1e4fd5044ff086',
    messagingSenderId: '240028515315',
    projectId: 'resqnow-12e6c',
    authDomain: 'resqnow-12e6c.firebaseapp.com',
    storageBucket: 'resqnow-12e6c.firebasestorage.app',
  );
}
